Feat/base error v2 initial implementations
c-commerce/charles-browser-sdk pull request #195
Opened 2022-07-20 09:42 UTC by TheHussein

2022-07-21 06:55 UTC, MaxAndDev approved these changes
LGTM

2022-07-25 06:02 UTC, eljefedelrodeodeljefe requested changes
See comments above

2022-07-25 06:02 UTC, eljefedelrodeodeljefe commented on src/entities/person/channel-user.ts
> +import { AxiosError } from 'axios'
nit: `import type { AxiosError } from 'axios'` should be enough

2022-07-27 12:51 UTC, eljefedelrodeodeljefe commented
@TheHussein added some fixes and tests that were necessary. PTAL and then let's go ahead with it.

2022-07-27 12:51 UTC, eljefedelrodeodeljefe approved these changes

2022-07-27 14:05 UTC, merged