Feat/add bulk delete endpoints
c-commerce/charles-browser-sdk pull request #214
Opened 2022-08-29 08:13 UTC by johnrogerz

https://app.clickup.com/t/24327122/TECH-3060

- add functions for deleteMany for the different entities

2022-08-29 08:14 UTC, TheHussein commented on src/entities/contact-list/contact-list.ts
> +    if (!Array.isArray(ids) || !ids.length) throw new TypeError('bulk deletion of contact lists requires IDs to be set.')
Use ErrorV2

2022-08-29 08:14 UTC, TheHussein commented on src/entities/message-subscription/message-subscription.ts
> +    if (!Array.isArray(id) || !id.length) throw new TypeError('bulk deletion of opt-ins requires IDs to be set.')
Same here

2022-08-29 08:15 UTC, TheHussein commented on src/entities/notification-campaign/notification-campaign.ts
> +    if (!Array.isArray(ids) || !ids.length) throw new TypeError('bulk deletion of campaigns requires IDs to be set.')
Same

2022-08-29 08:15 UTC, TheHussein commented on src/entities/person/person.ts
> +    if (!Array.isArray(ids) || !ids.length) throw new TypeError('bulk deletion of persons requires IDs to be set.')
4

2022-08-29 09:51 UTC, johnrogerz commented on src/entities/contact-list/contact-list.ts
> +    if (!Array.isArray(ids) || !ids.length) throw new TypeError('bulk deletion of contact lists requires IDs to be set.')
done

2022-08-29 09:52 UTC, johnrogerz commented on src/entities/message-subscription/message-subscription.ts
> +    if (!Array.isArray(id) || !id.length) throw new TypeError('bulk deletion of opt-ins requires IDs to be set.')
done

2022-08-29 09:52 UTC, johnrogerz commented on src/entities/notification-campaign/notification-campaign.ts
> +    if (!Array.isArray(ids) || !ids.length) throw new TypeError('bulk deletion of campaigns requires IDs to be set.')
done

2022-08-29 09:52 UTC, johnrogerz commented on src/entities/person/person.ts
> +    if (!Array.isArray(ids) || !ids.length) throw new TypeError('bulk deletion of persons requires IDs to be set.')
done

2022-08-29 10:16 UTC, TheHussein approved these changes
LGTM but would prefer @eljefedelrodeodeljefe signing off on pattern for new Error construction

2022-08-29 14:37 UTC, eljefedelrodeodeljefe approved these changes
I think we should implement on BaseEntity even though it is not implemented on all entities. But fine for me

2022-08-29 18:51 UTC, haayhappen requested changes
This needs some work to be aligned to BE

2022-08-29 18:51 UTC, haayhappen commented on src/entities/message-subscription-instance/message-subscription-instance.ts
> +}
This has changed now (req body & params)

2022-08-29 18:51 UTC, haayhappen commented on src/entities/message-subscription/message-subscription.ts
> +        url: `${this.universe.universeBase}/${this.endpoint}/`,
trailing slash

2022-08-29 18:51 UTC, haayhappen commented on src/entities/contact-list/contact-list.ts
> +        url: `${this.universe.universeBase}/${ContactLists.endpoint}/`,
trailing slash, also use qs to stringify deleteOptions (eg query params)

2022-08-29 18:51 UTC, haayhappen commented on src/entities/message-subscription/message-subscription.ts
> +    const { id, purge } = payload
changed

2022-08-29 18:51 UTC, haayhappen commented on src/entities/notification-campaign/notification-campaign.ts
> +        url: `${this.universe.universeBase}/${this.endpoint}/`,
trailing slash, missing qs

2022-08-29 18:51 UTC, haayhappen commented on src/entities/person/person.ts
> +        url: `${this.universe.universeBase}/${this.endpoint}/`,
trailing slash, missing qs

2022-08-29 20:21 UTC, haayhappen commented
Actually also agree with Rob to implement this on BaseEntity

2022-08-30 13:35 UTC, closed without merging

2022-08-30 13:36 UTC, johnrogerz commented
Superceded by #216