feat(img-proxy)
c-commerce/charles-browser-sdk pull request #88
Opened 2021-11-05 12:42 UTC by stnw

2021-11-05 16:12 UTC, eljefedelrodeodeljefe requested changes
Generally LGTM, but with a couple of comments to address, especially the `qs` bit

2021-11-05 16:12 UTC, eljefedelrodeodeljefe commented on package.json
> +    "query-string": "^7.0.1",
please remove this dependency, as the `qs` is doing exactly the same. Was there any reason for it? In any case we prefer `qs`, as it support everything the API suipports

2021-11-05 16:12 UTC, eljefedelrodeodeljefe commented on src/entities/image-proxy/image-proxy.ts
> +    return `${this.configuration.domain}/proxy/images?${queryString.stringify(this.getUrlParams(request))}`
see note above

2021-11-05 16:12 UTC, eljefedelrodeodeljefe commented on src/entities/image-proxy/image-proxy.ts
> +    }
can't you not just use normal object notation and use `qs` for the stringified version?

2021-11-05 16:12 UTC, eljefedelrodeodeljefe commented on src/universe/index.ts
> +  public async imgProxies (options?: EntityFetchOptions): Promise<imgProxy.ImageProxy[] | imgProxy.ImageProxyRawPayload[] | undefined> {
would prefer `s/imgProxies/imageProxies`

2021-11-05 16:12 UTC, eljefedelrodeodeljefe commented on src/entities/image-proxy/image-proxy.ts
> +      throw new UrlShortenerImgProxyError({ error })
probably missed the move to ImageProxy, no?

2021-11-10 14:49 UTC, MaiLinhGroup approved these changes
LGTM 🐻

2021-11-23 10:40 UTC, merged